import 'package:flutter/material.dart';
import 'package:food_app/model/meals.dart';
import './model/category.dart';
import './model/meals.dart';

const DUMMY_CATEGORIES =const [
  Category(id: 'c1', title: 'Italian', color: Colors.deepPurple),
  Category(id: 'c2', title: 'Mexican', color: Colors.orange),
  Category(id: 'c3', title: 'Light and Lovely', color: Colors.red),
  Category(id: 'c4', title: 'Exotic', color: Colors.purple),
  Category(id: 'c5', title: 'Veggies', color: Colors.grey),
  Category(id: 'c6', title: 'Asian', color: Colors.amber),
];

const DUMMY_MEALS = const [
  Meals(
      affordablility: Affordablility.Affordable,
      title: 'Spaghetti with Tomato sauce', id: 'm1', categoryIds: ['c1','c4'],
      complexity: Complexity.Simple,
      duration: 45, imageURL: 'https://media.istockphoto.com/photos/spaghetti-in-a-dish-on-a-white-background-picture-id1144823591?k=20&m=1144823591&s=612x612&w=0&h=6cuhQIP6Xmzu98wYGDnaxyF-Y4PBgfQiejTMQmqQKYQ=',
      ingredients: [
        'Extra virgin olive oil.',
        ' Fresh garlic.',
        'Meat and Hot pepper flakes.',
        'Red wine and Fresh or dried herbs.',
        'Cheese or Cream',
      ],
      isGlutenfree: true, isLactosefree: true,
      isVegan: true, isVegetarian: true,
      steps: [
        'Use a large pot. ...',
        'Load up the pot with lots of water.',
        'Salt the water.',
        'Bring the water to a full, rolling boil.',
        'Stir to keep the pasta from sticking.',
        'Test the pasta two minutes before its ready',
        'Save a scoop of pasta water.',
        'Drain, toss with sauce, and serve hot',
      ],
  ),
  Meals(affordablility: Affordablility.Pricey,
      title: 'Light and Lovely Chicken', id: 'm2',
      categoryIds: ['c3'], complexity: Complexity.Simple,
      duration: 90, imageURL: 'https://mediacdn.grabone.co.nz/asset/t2jBxZDABl/box=970x0',
      ingredients: [
    ' cinnamon', 'star anise', 'white pepper', 'red chile flakes', 'curry powder', 'cumin',
      ],
      isGlutenfree: true, isLactosefree: true,
      isVegan: true, isVegetarian: false,
      steps: [
        'Crack An Egg In It.',
        'Add Some Roasted Chicken.',
        'Sauteed Mushrooms In Ginger.',
        'Load It Up With Cheese.',
        'Sprinkle In Soy Sauce.',
        'Boil It In Broth Instead Of Water.',
        'Sprinkle Lime Juice On It.',
      ],
  ),
  Meals(
    affordablility: Affordablility.Pricey,
    title: 'Pizza', id: 'm3',
    categoryIds: ['c2'], complexity: Complexity.Challenging,
    duration: 35, isGlutenfree: true, isLactosefree: true,
    isVegan: true, isVegetarian: true,
    imageURL: 'https://img.onmanorama.com/content/dam/mm/en/food/features/images/2021/10/17/pizza.jpg',
    ingredients: [
      'Broccolini or broccoli (blanch first) and pancetta/speck/bacon.',
      'Potato, sausage, pancetta/speck/bacon.',
      'Gorgonzola and mushroom.',
      'Black olives, anchovies, capers.',
      'Gorgonzola, radicchio.',
      'Capers, anchovies, eggplant, capsicum.',
      'Mixed sliced mushrooms and garlic.',
    ],
    steps: [
      'Gather Ingredients. Heat the sauce while chopping up these ingredients.',
      'Prepare the Dough. This step takes some practice.',
      'Add the Toppings.',
      'Heat and Then Enjoy',
    ]
  ),
  Meals(affordablility: Affordablility.Luxurious,
      title: 'Veggies', id: 'm4', categoryIds: ['c5'], complexity: Complexity.Simple, duration: 20,
      imageURL: 'https://cdn.loveandlemons.com/wp-content/uploads/2021/04/green-salad.jpg',
      ingredients: [
        'Crumbled cheese, such as cotija or queso fresco',
        'Crema Mexicana or crème fraîche',
        'Chopped cilantro',
        'Chopped red onion',
        'Sliced avocado',
        'spinach',
        'Brocolli',
        'Beans',
        'Yellow bell pepper',
        'Carrots',
      ],
      isGlutenfree: false, isLactosefree: false, isVegan: true, isVegetarian: true,
      steps: [
        'Fry tortilla wedges until they are crisp and golden',
        'Simmer the fried tortillas in salsa.',
        'Serve the dish with garnishes and fried eggs, beans, or nopalitos.',
      ]),
  Meals(affordablility: Affordablility.Pricey,
      title: 'Pho',
      id: 'm5', categoryIds: ['c6'], complexity: Complexity.Simple, duration: 40,
      imageURL: 'https://www.recipetineats.com/wp-content/uploads/2019/04/Beef-Pho_6.jpg',
      ingredients: [
        'rice paper rolls',
        'Beef stock and thin rice noodles',
        'cinnamon sticks and cadromom pods',
        'coriander seeds, star anise',
        'whole clove, fresh herbs',
        'bean sprouts, onion,sauces',
      ],
      isGlutenfree: true, isLactosefree: false, isVegan: false, isVegetarian: false,
      steps: ['prep the protein',
      'make the broth',
        'prep the noodels',
        'sprinkle the herbs and spices',
        'serve with the sauces',
      ]),
  Meals(affordablility: Affordablility.Pricey, title:'Octopus', id: 'm6', categoryIds: ['c4'],
      complexity: Complexity.Hard, duration: 110,
      imageURL: 'https://miro.medium.com/max/1400/0*ms25qTKJKj60ZbCI',
      ingredients: [
        '1 yellow onion, coarsely chopped',
        '3 cloves garlic, peeled and crushed',
        '1 large bay leaf',
        '1 ½ teaspoons smoked Spanish paprika',
        '1 ½ teaspoons kosher salt',
        '1 tablespoon olive oil'
      ],
      isGlutenfree: false, isLactosefree: true,
      isVegan: false, isVegetarian: false,
      steps: [
        'Place chopped onion, garlic cloves, bay leaf, paprika, salt, and 1 tablespoon olive oil into saucepan.',
        'Cook and stir over medium-high heat until onions start to soften, about 5 minutes. Add white wine to create the braising liquid.',
        'Transfer octopus into braising liquid, turning to coat with the liquid. Cover; reduce heat to low.',
        'Simmer 20 minutes and turn octopus over. Continue cooking until octopus is tender, another 40 to 45 minutes.',
        'Cut octopus into 3 or 4 serving-size pieces. Brush with olive oil.',
        'Heat a grill pan or outdoor grill to high heat. Transfer octopus pieces to grill. Cook until flesh is seared, almost charred, 3 or 4 minutes'
      ])
];
